---
  - name: Install nginx
    sudo: yes
    apt:  pkg=nginx state=latest

  - name: Ensure nginx log directory exists
    sudo: yes
    file: dest={{ nginx.log_directory }} state=directory

  - name: Change default nginx site
    sudo: yes
    template: src={{ nginx.config_template }}.tpl dest=/etc/nginx/sites-available/default
    notify: restart nginx