---
- hosts: all
  vars:
    #
    # Base system config
    #
    base:
      web_root: /var/www/web
      #
      # System packages
      #
      system_packages:
        - curl
        - wget
        - build-essential
        - python-software-properties
        - vim
        - nodejs
        - npm
        - mcrypt
        - git
        #- memcached
        #- sqlite3
    #
    # Nginx configuration
    #
    nginx:
      doc_root: /var/www/web
      log_directory: /var/log/nginx/www
      server_name: application.dev
      #
      # Watch ansible/roles/nginx/template for nginx config templates or add
      #
      config_template: symfony2
    #
    # PHP config
    #
    php5:
      php_ppa_repository: ppa:ondrej/php5-5.6
      #
      # PHP packages
      #
      packages:
        - { name: dev, package: php5-dev }
        - { name: pear, package: php-pear }
        - { name: xdebug, package: php5-xdebug }
        - { name: curl, package: php5-curl }
        - { name: mcrypt, package: php5-mcrypt }
        - { name: mysql, package: php5-mysql }
        #- { name: sqlite, package: php5-sqlite }
        #- { name: memcached, package: php5-memcached }
        #- { name: redis, package: php5-redis }
      #
      # PHP extension
      #
      extensions:
        - { name: xhprof, package: pecl.php.net/xhprof-beta }
  roles:
    - base
    - nginx
    - php5-fpm
    - php5
    - composer
    - mysql
    - phpunit
    #- redis